backend:
  name: git-gateway
media_folder: 'assets/uploads'
sass:
  style: compressed
collections:
  - name: 'posts'
    label: 'Post'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'text' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'project'
    label: 'Project'
    folder: '_projects/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'text' }
      - { label: 'Start date', name: 'start_date', widget: 'date' }
      - { label: 'Finished?', name: 'finished', widget: 'boolean' }
      - { label: 'Finish date', name: 'finish_date', widget: 'date' }
      - { label: 'External link', name: 'external_link', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }